AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - '**/vendor/**/.*'
    - '**/node_modules/**/*'
    - './bin/*'
    - './config/**/*'
    - './app/channels/**/*'
    - './db/schema.rb'
    - './db/migrate/*'
    - './test/*'
Metrics/LineLength:
  Max: 130
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'task', 'configure']
Metrics/AbcSize:
  Max: 22
Metrics/MethodLength:
  Max: 16

Style/Documentation:
  Enabled: false
